### ISSUE TITLE
How to use roman numerals in front matter and decimal in the main body?

### ISSUE THREAD

**Issue by yihui** [rstudio/pagedown#1]
The roman counter can be obtained via `content: counter(page, lower-roman);` (https://alistapart.com/article/boom), but the problem is that I cannot reset the counter when Chapter 1 starts, i.e. the page numbers will be like `i, ii, iii, iv, ..., viii, 9, 10`.

`counter-reset: page` doesn't work.

**Comment by RLesur** [comment]
The current implementation of `target-counter(attr(href), page)` does not seem compatible with `counter-reset: page` (see [here](https://gitlab.pagedmedia.org/tools/pagedjs/blob/master/src/modules/generated-content/target-counters.js#L80)).

I don't think we can handle with this issue without any development in paged.js.

**Comment by RLesur** [comment]
@fchasen asked me to open an issue for this one. See https://gitlab.pagedmedia.org/tools/pagedjs/issues/74

**Comment by RLesur** [comment]
After upgrading to Paged.js 0.1.28 (https://github.com/rstudio/pagedown/commit/3168deb12de81d74161754c543ba8720b7abe826), the `counter-reset: page` rule is now working with some limitations.
For instance, the following rule is OK:
```css
#introduction {
  counter-reset: page;
}
```

However, this doesn't work yet:
```css
.section :first-of-type {
  counter-reset: page;
}
```
The page counter is reset on each page which contains an element of class `section` (in other words, each page because of the design of Paged.js).
I think a specific Polisher hook could be develop. However, I'm not yet familiar with the Polisher.

For now, I have a simple proposal.
We could use a specific class in the default CSS as follows:
```css
.reset-page {
  counter-reset: page;
}
```
Therefore, the user could use it with R Markdown:
```markdown
# Introduction {.reset-page}
```
