### ISSUE TITLE
Page numbers disappeared from page reference 

### ISSUE THREAD

**Issue by atusy** [rstudio/pagedown#120]
As far as I checked by rendering `inst/examples/index.Rmd`, the page numbers disappeared since 216c09a9435788b0b4f2b993828ca91b8a3156d8.

Below is a screenshot of current https://pagedown.rbind.io/#page-references

![image](https://user-images.githubusercontent.com/30277794/60905039-372a3400-a2af-11e9-9728-63f56f863d90.png)

**Comment by yihui** [comment]
@RLesur After this issue is resolved, I'd like to upload a new version of **pagedown** to CRAN because it has been almost half a year since the last update. No hurry, though.

**Comment by RLesur** [comment]
@yihui We are sync. I precisely wanted to inspect this issue today before going on holidays.

**Comment by RLesur** [comment]
@atusy Thanks a lot for having spotted the exact commit. This was super helpful! 
The problem comes more precisely from https://github.com/rstudio/pagedown/commit/216c09a9435788b0b4f2b993828ca91b8a3156d8#diff-b2e946e796db5bbbe9e9b33dd905e4b7L184
I don't know why I've removed this `<div>`. Sorry for that!

There's another problem to fix: with **Pandoc 2.7.3**, `<a></a>` elements are present in code blocks. Therefore, the CSS introduces pages reference like that:
 
![pandoc273](https://user-images.githubusercontent.com/19177171/61185182-7dd4b100-a656-11e9-887f-7f534b581bca.png)

**Comment by atusy** [comment]
Thank you, too!!
I locally checked it works now :smile:

**Comment by yihui** [comment]
@RLesur Perfect! Please let me know whenever you feel you are ready for the next release, and I'll upload it to CRAN. We certainly don't have to address all issues. I think we have had enough items in NEWS.md that can warrant a CRAN update.

**Comment by RLesur** [comment]
@yihui I will leave tomorrow and won't be able to contribute to open source projects for three weeks.
I think you can release 0.3 when you want.

**Comment by yihui** [comment]
Sounds good. Thank you!

**Comment by yihui** [comment]
@RLesur FYI, **pagedown** v0.3 is on CRAN now.
