### ISSUE TITLE
Workaround needed to knit for `self_contained: false` optioned output

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/pagedown#132]
I am using R without RStudio as it is not accessible to blind people.
Whenever I knit Rmd files, I have used `rmarkdown::render()` command manually.
However, I have found that `pagedown::html-paged()` output that includes `self_contained: false` option in YAML requires different knitting workaround instead of `rmarkdown::render()`.
I assume that might be `xaringan::infinite_moon_reader()`. However, that function is not available for non-RStudio users. Would you mind implementing any alternative solutions?

**Comment by yihui** [comment]
`xaringan::infinite_moon_reader()` is available to all R users. You don't have to use RStudio to call an R function. The only difference for non-RStudio users is that you have to pass the Rmd filename to this function since it won't be able to automatically discover the current open Rmd file in the editor.

**Comment by jooyoungseo** [comment]
Wow, yes it works after passing the file name! Thank you so much @yihui for your kind and detailed explanation.
