### ISSUE TITLE
how to change the photo position in html_resume

### ISSUE THREAD

**Issue by jywang2016** [rstudio/pagedown#139]
Hi,

```
---
title: "Lijia Yu's resume"
author: Lijia Yu
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
---

Aside
================================================================================


![Lijia Yu](https://avatars1.githubusercontent.com/u/895125?s=400&v=4){width=80%}

```

The photo position is not aligned with the introduction text on the left side. So ,is there a way to make the photo position go up a little bit? 

![issues](https://user-images.githubusercontent.com/33275527/64476548-6fbc9000-d1c2-11e9-9449-99a0d8026cab.png)

Here is what I expect.

![expect](https://user-images.githubusercontent.com/33275527/64476553-7a772500-d1c2-11e9-8a89-d9cdec5f94bc.png)

Thanks for your help.

**Comment by RLesur** [comment]
It is possible to achieve using CSS.
In order to understand how to adapt the CSS styles to your need, the best thing to do is to use Chrome Developer Tools (F12 or right click on the page then _Inspect_).

When you do this, you get this screen:
![resume-img](https://user-images.githubusercontent.com/19177171/64476728-03766800-d193-11e9-9113-22d349bea6b6.png)

The vertical space comes first from the padding of the `div` element of class `aside`. There is also a vertical space due to the margin of its `p` element (the one which contains the image).

Therefore, you can get rid off this vertical space like this:

    ---
    title: "Lijia Yu's resume"
    author: Lijia Yu
    date: "`r Sys.Date()`"
    output:
      pagedown::html_resume:
        # set it to true for a self-contained HTML page but it'll take longer to render
        self_contained: false
    ---
    
    ```{css, echo=FALSE}
    .aside {
      padding-top: 0;
    }
    
    .aside > p:first-of-type {
      margin-top: 0;
    }
    ```
    
    Aside
    ================================================================================
    
    
    ![Lijia Yu](https://avatars1.githubusercontent.com/u/895125?s=400&v=4){width=80%}

**Comment by jywang2016** [comment]
Great！ It works well for me. :smile:

Thanks for your help.
