### ISSUE TITLE
Strange behaviors of block elements in paged-footnotes

### ISSUE THREAD

**Issue by atusy** [rstudio/pagedown#156]
For example, a footnote with bullet list in html is rendered in the body, and leaves the empty footnote at the bottom of the page.
A footnote with bullet list in markdown is collapsed.

They work fine when `paged-footnotes: false`.

## Source Rmd

````md
---
output: pagedown::html_paged
paged-footnotes: true
---

A sentence.[^html]

Another sentence.[^md]



[^html]: <ul><li>a</li><li>b</li></ul>

[^md]:
    - a
    - b
````

## Output

![image](https://user-images.githubusercontent.com/30277794/70840796-34cc9700-1e58-11ea-8c61-59ec2048262c.png)

**Comment by RLesur** [comment]
`paged-footnotes: true` only supports **inline footnotes**.   
The reason comes the W3C CSS Generated Content for Paged Media Module Working Draft. As you can see [here](https://www.w3.org/TR/css-gcpm-3/#creating-footnotes), these specifications are only defined for inline elements. There is no support for block elements like lists.

In **pagedown**, `paged-footnotes: true` involves this Pandoc filter <https://github.com/rstudio/pagedown/blob/master/inst/resources/lua/footnotes.lua> which turns block elements into inline elements. The main function used in this filter is [pandoc.utils.blocks_to_inlines()](https://pandoc.org/lua-filters.html#utils-blocks_to_inlines). The second part of `paged-footnotes: true` is this Paged.js handler: https://github.com/rstudio/pagedown/blob/d96b5e210a34b493b0a4d1ea8e02983cb0bee912/inst/resources/js/hooks.js#L208-L321

In the example, the markdown footnote is collapsed because the list (which is a block element) is turned into an inline span (this is the job of the Pandoc filter).

For the HTML footnote, the reason is different. Pandoc parses this markup as raw HTML as you can see in the JSON serialization of the AST:

```json
{"blocks":[{"t":"Para","c":[{"t":"Str","c":"A"},{"t":"Space"},{"t":"Str","c":"sentence."},{"t":"Span","c":[["fn1",["footnote"],[["data-pagedown-footnote-number","1"],["style","white-space: pre-line;"]]],[{"t":"RawInline","c":["html","<ul>"]},{"t":"Str","c":"\n"},{"t":"RawInline","c":["html","<li>"]},{"t":"Str","c":"\na\n"},{"t":"RawInline","c":["html","</li>"]},{"t":"Str","c":"\n"},{"t":"RawInline","c":["html","<li>"]},{"t":"Str","c":"\nb\n"},{"t":"RawInline","c":["html","</li>"]},{"t":"Str","c":"\n"},{"t":"RawInline","c":["html","</ul>"]}]]}]},{"t":"Para","c":[{"t":"Str","c":"Another"},{"t":"Space"},{"t":"Str","c":"sentence."},{"t":"Span","c":[["fn2",["footnote"],[["data-pagedown-footnote-number","2"],["style","white-space: pre-line;"]]],[{"t":"Str","c":"ab"}]]}]}],"pandoc-api-version":[1,17,5,4],"meta":{"newpage_html_class":{"t":"MetaString","c":"page-break-after"},"paged-footnotes":{"t":"MetaBool","c":true},"output":{"t":"MetaMap","c":{"pagedown::html_paged":{"t":"MetaMap","c":{"keep_md":{"t":"MetaBool","c":true}}}}}}}
```

Pandoc's HTML writer takes this raw HTML asis. So, the generated markup is:

```html
<p>A sentence.<span id="fn1" class="footnote" style="white-space: pre-line;" data-pagedown-footnote-number="1"><ul>
<li>
a
</li>
<li>
b
</li>
</ul></span></p>
```

Having a block element like `<ul></ul>` in a `<p>` element is illegal: this markup is invalid.  
Browsers are quite flexible: they add a missing closing `</p>` tag just before the opening `<ul>` tag and by consequence a closing `</span>` tag too. So, the footnote is "reduced" to this void span element:

```html
<span id="fn1" class="footnote" style="white-space: pre-line;" data-pagedown-footnote-number="1"></span>
```

I think I will add in the documentation that `paged-footnotes: true` only works for inline footnotes.

**Comment by atusy** [comment]
Thanks a lot for the explanation, and for the plan to update the documentation!!
It makes sense.

**Comment by RLesur** [comment]
@atusy Thanks a lot for the report! I've updated the documentation in https://github.com/rstudio/pagedown/commit/3f765d9f7c3164bca5d2bddb40a537d087788184.

**Comment by atusy** [comment]
Great! Thank you!
