### ISSUE TITLE
Pagedown: Not printing an element when kniting

### ISSUE THREAD

**Issue by AnabelleLaurent** [rstudio/pagedown#167]
Hi,
In my Talks rubric (Talks {data-icon=comment}) I have multiple talks and when I knit the last one does not show up. I am wondering if it is due to the pagebreak as the last talk should go on the next page. Instead I have the next rubric. 
Thank you

**Comment by cderv** [comment]
Can you share your source code ? Or an example that reproduce the issue ? 
That could help us help you here, or find the issue if any. 
Thank you

**Comment by AnabelleLaurent** [comment]
![resume_issue](https://user-images.githubusercontent.com/26171337/75100493-ae3ce000-5593-11ea-9978-89f05cfbb4d6.png)

Here is the code `### Ranking yields of energy crops: A meta-analysis using direct and indirect comparisons ###

ASA, CSSA & SSSA International meeting, November 2-5

Long Beach, USA

2014

**A. Laurent**, E. Pelzer, C. Loyce, D. Makowski.`

The missing talk that should appear before the teaching experience section. 
I do believe it is something related with the pagebreak because if I delete some talks, I am able to see the missing one

**Comment by cderv** [comment]
I am trying to reproduce using the `html_resume` template inlcuded in pagedown and adding some bullets to one of the main section. Currently, I can't reproduce any bugs. 

* Did you try to update 📦 already ? `remotes::install_github("rstudio/pagedown")`
* If you still encounter the bug, can you try to reproduce it using the `html_resume` template so that you could share a Rmd file that recreate the bug for you ? I assume here you can't share your actual resume. 

Thank you

**Comment by AnabelleLaurent** [comment]
It worked ! Thank you so much
Anabelle

**Comment by cderv** [comment]
As a wise man said, ["when in doubt, upgrade"](https://yihui.org/en/2017/05/when-in-doubt-upgrade/) 😉 😄 

Glad it works ! 🎉 Happy resume with pagedown !
