### ISSUE TITLE
another pagedown::html_resume pagebreak issue

### ISSUE THREAD

**Issue by kevinrue** [rstudio/pagedown#170]
Hello.

Thanks a gazillion for the stunning look of pagedown resumes!
I'm running into am issue very similar to #153  for both the HTML and PDF versions.

My CV is available here: [http://kevinrue.github.io/files/Kevin-Rue-CV.html](https://kevinrue.github.io/files/Kevin-Rue-CV.html#training-and-courses)
See the entry ["Bioconductor for Genomic Data Science"](url).

The "details" section of this entry, namely:
> This course is part of the Genomic Data Science Specialization.

appears on the following page, without respecting the indentation level.

Is there a way to "push" the whole entry to the next page, when it doesn't completely fit at the end of the previous page?

Thanks again!

**Comment by RLesur** [comment]
Hi @kevinrue,

Glad you like the resume template!

> Is there a way to "push" the whole entry to the next page, when it doesn't completely fit at the end of the previous page?

I've fixed that in https://github.com/rstudio/pagedown/commit/affb42f79cf758dd657b72cfbd84bddd483ce813

Please, can you can try with the development version of **pagedown** and tell me whether the problem is fixed for your resume?  
You can install the development version using: 

```r
remotes::install_github("rstudio/pagedown")
```

**Comment by kevinrue** [comment]
The fix works perfectly!

It looks flawless to me now.
https://kevinrue.github.io/files/Kevin-Rue-CV.html

Thanks a ton!
All the best
