### ISSUE TITLE
chrome_print keypress navigation

### ISSUE THREAD

**Issue by yonicd** [rstudio/pagedown#192]
chrome_print navigates with a keypress of ArrowDown, how can this be controled? I am trying to use ArrowRight to navigate a xaringan slide deck with panels in the slides.

**Comment by cderv** [comment]
Hi @yonicd, 

What do you mean by Navigation ?  `pagedown::chrome_print` is basically just using websocket connection to the devtools protocol to load the Page Url and required resource before calling [`Page.printToPDF`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF).  It should be the same as clicking on Print PDF in chrome. You can pass some options to `Page.printToPDF` but I don't see anything related to navigation.

Can you give an example of what you want to do exactly ?

**Comment by cderv** [comment]
I guess this ? 
> Any ideas how to get decktape.js or chrome_page to convert a slide deck with panelsets to a pdf that can toggle through the panel sets as new pages in the pdf?
>
> The main problem is that the slides get toggled through with a --key=ArrowRight instead of ArrowDown when using the generic command.

**Comment by cderv** [comment]
From https://github.com/gadenbuie/xaringanExtra/issues/67#issuecomment-715201803

> I don't think this is an issue with the printing tool. In case of chrome, as I said in rstudio/pagedown#192 (comment), it just uses the Pages.printToPDF method of Chrome. I don't think it "navigates" the slide.

**Comment by RLesur** [comment]
IMO, the issue comes from the **xaringanExtra** panelset plugin.
Basically, `chrome_print()` prints a page with CSS media `print`. 

remark.js handles the print mode (see [here](https://github.com/gnab/remark/blob/48397a18ba107f3bd8b39b18782de864be9e3128/src/remark/views/slideshowView.js#L202-L229) and [here](https://github.com/gnab/remark/blob/48397a18ba107f3bd8b39b18782de864be9e3128/src/remark/components/printing/printing.js)) by [detecting the `print` media](https://github.com/gnab/remark/blob/48397a18ba107f3bd8b39b18782de864be9e3128/src/remark/components/printing/printing.js#L26-L28).

However, the **xaringanExtra** [panelset plugin](https://github.com/gadenbuie/xaringanExtra/blob/aebe20a761c018687a7dc8e5c92bdab64b97de00/inst/panelset/panelset.js) does not manage the `print` media. Particularly, it does not create new slides (`slideshow.getSlideCount()` gives the same result with or without panelset).

_Closing this issue in favor https://github.com/gadenbuie/xaringanExtra/issues/45._

**Comment by yonicd** [comment]
Thanks for the explanation. 

Is there a different tabset library that could work better with printing?
