### ISSUE TITLE
Problem with rendering flextable when using equations in pagedown

### ISSUE THREAD

**Issue by sylvaine31** [rstudio/pagedown#332]
Hi, 
I'm not sure wheter it is a flextable or a pagedown issue.
When using equations in a pagedown::html_paged Rmd, flextable does not render.
my reprex : 

````
---
title: "Blabla"
author: "ploupi"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: pagedown::html_paged
---

# mtcars with flextable does not render

```{r echo=TRUE}

ploup <- mtcars |> 
  head() |> 
  dplyr::select(mpg, cyl)

  flextable::flextable(ploup) |> 
    flextable::autofit()

```

# mtcars with print renders

``` {r echo=TRUE}

print(ploup)

```

# the equation
$$
Y = \frac{a_{x}-b} {c}
$$
````

If I replace the equation by a R chunk , the flextable renders without problem : 
````
 ```{r equation1, echo = FALSE}

equatags::transform_mathjax("Y = \\frac{a_{x}-b} {c}") |> 
  htmltools::HTML()
 ```
````

**Comment by cderv** [comment]
👋 @sylvaine31 

First, advice on formatting: Use one more backtick to wrap you rmd source. See https://yihui.org/issue/#please-format-your-issue-correctly

Then, advice on reprex: With newer R, use `|>` and not `%>%` which allows in reprex to avoid having to laod **magrittr** (which is missing in our example here). 

Regarding the issue, it seems there are some changes in **flextable** that requires some adaptation in **pagedown**. 

Using **flextable** 0.8.5, it works but then starting from 0.8.6 it fails with table not showing. 

So I need to check with @davidgohel what are the changes between these version. Repo has not tagged version so not easy to compare the change, but I'll do a bit of archeology.

**Comment by cderv** [comment]
Thanks for CRAN snapshot github repo, we can access the difference in the version 
- https://github.com/cran/flextable/compare/0.8.5...0.8.6

Not the commit history, but it could give us some hint still

**Comment by cderv** [comment]
It could be related to `tabwid.js` addition which may not run correctly with paged.js applying 🤔

**Comment by cderv** [comment]
And this search lead me to this commit
- https://github.com/davidgohel/flextable/commit/439d93c55339b0d1ff7929fbfa80d470adf75308

I think that **flextable** now always output shadow dom, and #216 still applies because the `ft.shadow` option is not existing anymore in **flextable**  (https://github.com/davidgohel/flextable/commit/439d93c55339b0d1ff7929fbfa80d470adf75308#diff-f0c168982bc3b1afb5f98bd5e0230be9a96126d723db777bfde5b3dfeacf9b00L1012) 

@davidgohel I'll see what I can do in **pagedown** but if there is a way to still not use shadow dom in paged.js context, it would be cool. 

Otherwise, it will need to wait for an update in Paged.js inside pagedown but I am not sure that paged.js really support shadow dom
- https://gitlab.coko.foundation/pagedjs/pagedjs/-/issues/148
- https://gitlab.coko.foundation/pagedjs/pagedjs/-/issues/120

So we may be blocked here. 🤔

**Comment by davidgohel** [comment]
Hi @cderv 

Is there a way to detect with knitr (or any option) that the format is pagedown? Something like `knitr::is_html_output()`?

**Comment by yihui** [comment]
We don't, but we can set a flag similar to https://github.com/rstudio/pagedown/blob/410def190672fb3f854be7f89ac0200d80b79ec6/R/paged.R#L176-L178

I feel the flag should be set in `opts_knit` instead of `opts_chunk` since it's global to the document instead of individual chunks.

With that flag (say, named `is.paged.js`), **flextable** can detect `knitr::opts_knit$get('is.pagedjs')`.

**Comment by davidgohel** [comment]
that would be great, I could read `knitr::opts_knit$get('is.pagedjs')` in flextable and you could remove that `fmt$knitr$opts_chunk[['ft.shadow']] = FALSE` in pagedown

**Comment by cderv** [comment]
@davidgohel you can try out https://github.com/rstudio/pagedown/pull/333

I have kept `fmt$knitr$opts_chunk[['ft.shadow']] = FALSE` for backward compatibility with older flextable

**Comment by davidgohel** [comment]
@sylvaine31 the fix has been applied in 'flextable' now, and you should be able to display flextables again with dev version of 'pagedown' and dev version of flextable.

**Comment by sylvaine31** [comment]
Hi @cderv  and @davidgohel , 
I recently update all my packages and the problem came back, flextable is shadow if there is an equation in the Rmd.

flextable 0.9.11, 
R 4.3.3, 
pagedown 0.23





````
---
title: "test"
author: "moi"
output: 
 pagedown::html_paged:
    toc: true
    toc_depth: 2
  toc-title: "Sommaire"
paged-footnotes: true
---

$$revenu\ mensuel\ ménage = revenu\ (€/UC/an) \times \frac{nombre\ unités\ consomation}{12 \times nombre\ ménages\ fiscaux}$$

## Blabla



bloublou

```{r echo=FALSE}

table_plafond <- tibble::tribble(
  ~`Une colonne`, ~`Une autre`,
  "plip", "plap"
) 


flextable::flextable(table_plafond)
```
````

I found a turn-around by converting mathjax in HTML


````
```{r, results='asis', echo=FALSE}
equatags::transform_mathjax("revenu\\ mensuel\\ ménage = revenu\\ (€/UC/an) \\times \\frac{nombre\\ unités\\ consomation}{12 \\times nombre\\ ménages\\ fiscaux}") %>% 
  htmltools::HTML()


```
````
