### ISSUE TITLE
html_resume : page break and section alignment

### ISSUE THREAD

**Issue by bernardkaplan** [rstudio/pagedown#50]
When a section spreads over two pages the alignment gets wrong on the second one.
I took a screenshot of a slightly modified version of the template resume to illustrate my point.

- Is there a way to fix this ?
- Otherwise is it possible to force a page break just before the section that will span over two pages ?

<img width="834" alt="html_resume page break and section alignment" src="https://user-images.githubusercontent.com/16972087/51033821-e6a67800-15a4-11e9-87fe-c7514a7e49e3.png">

**Comment by RLesur** [comment]
This issue is documented in the section 3.1 of the pagedown documentation here https://pagedown.rbind.io/
You can try the solution provided in the documentation or the following one:
```css
.main-block {
  break-inside: avoid;
}
```

It is possible to force page breaks using the CSS rule `page-break-after: always;` or `break-after: page;` (equivalent).
For instance, you can create a custom CSS class:
```css
.break-after-me {
  break-after: page;
}
```
and apply this class to section. For instance
```markdown
Research Experience {data-icon=laptop .break-after-me}
--------------------------------------------------------------------------------
```

**Comment by Xinzhu-Fang** [comment]
where I am supposed to define these css classes?

**Comment by xiaosongz** [comment]
Update 1/2/2022

it seems the use the `avoid-column` works better for some cases.

```
/* avoid breaks in columns, this will prevent the experience time axis from break into seperate pages  */

.blocks {
    break-inside: avoid-column;
}
```
