### ISSUE TITLE
html_resume issues with months

### ISSUE THREAD

**Issue by lgnbhl** [rstudio/pagedown#51]
Thank you very much for this fantastic package!

Using Chrome and your skeleton, there is a bug with the line when adding months.
![html_resume_issue1](https://user-images.githubusercontent.com/29467632/51435879-75597a00-1cb4-11e9-97ef-e34a6e5d551a.png)

I tried with Month abbreviations. But sadly the date doesn't render on a single line and it doesn't look good on my own resume.
![html_resume_issue2](https://user-images.githubusercontent.com/29467632/51435880-7a1e2e00-1cb4-11e9-8473-7523ddfa4966.png)

Would it be possible to fix these issues? Or how can I add months on my resume?

**Comment by RLesur** [comment]
@lgnbhl Glad you like pagedown!
As a hotfix, I can propose you to add the following CSS rules to your `Rmd` files:

    ---
    title: "Lijia Yu's resume"
    author: Lijia Yu
    date: "`r Sys.Date()`"
    output:
      pagedown::html_resume:
        # set it to true for a self-contained HTML page but it'll take longer to render
        self_contained: false
    ---
    
    ```{css, echo=FALSE}
    .date {
      --decorator-horizontal-margin: 0.1in;
      max-width: var(--date-block-width);
    }
    .date span {
      text-align: center;
    }
    .date span:nth-child(2)::before {
      right: 0;
    }
    ```
    
    Aside
    ================================================================================
    
    
    ![Lijia Yu](https://avatars1.githubusercontent.com/u/895125?s=400&v=4){width=80%}
    
    ...

Here's a screenshot I got with these rules.
![capture du 2019-01-20 09-09-04](https://user-images.githubusercontent.com/19177171/51436742-264f1d00-1c93-11e9-9e3b-46038f38ef67.png)

Since this is a hotfix I've done quickly, I'ld prefer that you take some time to test it.
Tell us if this is OK for you.

**Comment by lgnbhl** [comment]
It works perfectly. Thank you!

**Comment by RLesur** [comment]
@yihui I wonder whether we should modify `resume.css` for this.

**Comment by yihui** [comment]
I think we should.
