### ISSUE TITLE
How to remove urls inserted after links?

### ISSUE THREAD

**Issue by paceafenet** [rstudio/pagedown#89]
Based on other R Markdown outputs, I would expect that [tag](html address) would read as 'tag' in the new document. The full url is still shown in the rendered document (see html_paged example in Readme).

**Comment by RLesur** [comment]
> The full url is still shown in the rendered document 

This is the expected behaviour in `pagedown::html_paged` documents.
The motivation is detailed in [the documentation](https://pagedown.rbind.io/#links), see section 4.3 _Links_.

If you want to get rid off these urls, please insert this CSS rule in your documents:

```css
a[href^="http"]:not([class="uri"])::after {
  content: "";
}
```
Therefore, the urls will not be printed (I still don't understand the need of using links in this context).
