### ISSUE TITLE
How to use pagedown html feature to print table in landscape format?

### ISSUE THREAD

**Issue by koliii** [rstudio/pagedown#96]

**Comment by RLesur** [comment]
There are plenty of great resources to learn CSS on the web: StackOverflow, [MDN](https://developer.mozilla.org/), [CSS-Tricks](https://css-tricks.com/)... and obviously Google.
You can easily find many solutions to your problem. 

My favourite trick to answer this question is:
- rotate by 90deg using the [`writing-mode`](https://developer.mozilla.org/docs/Web/CSS/writing-mode) property with the `vertical-rl` value, see [this CSS-Tricks article](https://css-tricks.com/almanac/properties/w/writing-mode/) with nice examples.
- rotate by -90deg using the previous trick and combine with the [`transform`](https://developer.mozilla.org/docs/Web/CSS/transform) property using the [`rotate()`](https://developer.mozilla.org/docs/Web/CSS/transform-function/rotate) function.

Do not hesitate to adapt/combine this answer with other CSS rules.

Here is a minimal `Rmd` file with examples:

    ---
    title: "Print tables in landscape format"
    output:
      pagedown::html_paged:
        self_contained: false
    ---
    
    # Rotate 90 deg
    
    ```{css}
    .rotate90 {
      writing-mode: vertical-rl;
      margin-right: 0;
    }
    ```
    
    ```{r, echo=FALSE}
    knitr::kable(
      head(iris[, -5]), 
      caption = 'An example table.', 
      format = 'html', 
      table.attr = 'class="rotate90"'
    )
    ```
    
    # Rotate 270 deg
    
    ```{css}
    .rotate270 {
      writing-mode: vertical-rl;
      transform: rotate(180deg);
      margin-left: 0;
    }
    ```
    
    ```{r, echo=FALSE}
    knitr::kable(
      head(iris[, -5]), 
      caption = 'An example table.', 
      format = 'html', 
      table.attr = 'class="rotate270"'
    )
    ```

**Comment by koliii** [comment]
Surprisingly, using this technique, my document processing is going on and on and on. In the Mozilla browser, the 50 pages document has already produced empty 350 pages and still continuing.

**Comment by RLesur** [comment]
This is an infinite loop. This problem is often observed when the content height is greater than the page height and `page-break-inside: avoid;` is used.
The most recent versions of **Paged.js** fix some of them.
I recognize that large or long contents are challenging: you have to control their width/height. 
In this case, I like to use `iframe`s as in https://github.com/rstudio/pagedown/pull/87

@yihui I think helpers for long or large tables could be integrated in **pagedown** by using the `autoscaling-iframe` HTML custom element of https://github.com/rstudio/pagedown/pull/87

**Comment by koliii** [comment]
I used bookdown instead of pagedown.

**Comment by RLesur** [comment]
I am not sure to understand your problem. Could you send a reproducible example?
